name: "WebMySocket"
description: "My first websocket!"
version: "1.0.5"
slug: "webmysocket"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
  9123/tcp: 9123
  88/tcp: 88
websocket_url: "ws://localhost:3000"
device_id: "abcde"
hassio_api: true
host_dbus: true
host_network: true
# Hvis ingress er n√∏dvendigt
ingress: true
ingress_port: 88